---
title: "Basketball shot charts with R"
output: html_document
date: '2022-07-20'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(BasketballAnalyzeR)
library(nbastatR)
library(plotly)
library(jsonlite)
library(janitor)
library(extrafont)
library(ggrepel)
library(scales)
library(teamcolors)
library(zoo)
library(future)
library(lubridate)

RNGkind(sample.kind = "Rounding")
Sys.setenv("VROOM_CONNECTION_SIZE" = 2*131072)
```

```{r}

PbP <- PbPmanipulation(PbP.BDB)
str(PbP)
subdata <- subset(PbP, player=="Stephen Curry")


subdata %>% ggplot(aes(original_x, original_y)) +
  geom_point()

subdata$xx <- subdata$original_x/10
subdata$yy <- subdata$original_y/10-41.75

shotchart(data=subdata, x="xx", y="yy", scatter = T,
          pt.col = "blue",
          bg.col = "yellow")

shotchart(data=subdata, x="xx", y="yy", scatter = T, 
          z = 'result',
          bg.col = "black",
          courtline.col = "white",
          palette = 'hot')

shotchart(data=subdata, x="xx", y="yy", scatter = T, 
          num.sect = 5,
          type = "sectors",
          z = 'playlength')


shotchart(data=subdata, x="xx", y="yy", scatter = F, 
          num.sect = 5,
          type = "sectors",
          z = 'playlength',
          result = 'result')


```

#interactive plot
```{r}


Pbox.sel <- subset(Pbox, MIN >= 500)
attach(Pbox.sel)
X <- data.frame(Player, AST/MIN, TOV/MIN, PTSpm = PTS/MIN)
Xnomin <- data.frame(Player, AST, TOV, PTS)
detach(Pbox.sel)

#do this for points, not turnovers
Xnomin <- Xnomin %>% mutate(Shooter = case_when(
  PTS < 581 ~ "Hesitant",
  (PTS >= 581 & PTS < 1000) ~ "2nd option",
  PTS >= 1000 ~ "Shooter")
  )
mypal <- colorRampPalette(c("blue", "yellow", "red"))

p6 <- scatterplot(Xnomin, data.var = c("AST", "TOV"),
                  z.var = "PTS", 
                  palette = mypal,
                  labels = Xnomin$Player)

p6 
p6 + geom_smooth(aes(x = Xnomin$AST, y = Xnomin$TOV), method = lm)
ggplotly(p6, tooltip = "text")


p7 <- Xnomin %>% ggplot(aes(x = AST, y = TOV, color = Shooter)) +
  geom_point() +
  scale_color_manual(values = c("yellow", "red",  "green" ), aesthetics = "color")

p7
ggplotly(p7, tooltip = "all")

data <- Pbox[1:50, c("PTS","P3M","P2M","OREB","Team")]
scatterplot(data, data.var=1:4, z.var="Team")

```

#looking at time to shoot vs time elapsed in game
```{r}
shots <- PbP %>% filter(ShotType %in% c("2P", "3P"))

shots <- shots %>% filter(playlength <= 24) #somehow there are 283 plays longer than 24 seconds

#take out overtime games
shots <- shots %>% filter(totalTime <= 2880)

shots %>% ggplot(aes(x = playlength, y = result)) + geom_boxplot()

shots %>% ggplot(aes(x = totalTime, y = playlength)) + geom_point() + geom_smooth(method = "lm") + facet_wrap(~ result)

shots %>% group_by(result) %>% summarise(mean_time = mean(playlength))

per1 <- shots %>% filter(totalTime <= 720) %>% group_by(totalTime) %>% summarise(mean_time = mean(playlength))

per1 %>% ggplot(aes(x = totalTime, y = mean_time)) + geom_point()

perall <- shots %>% group_by(totalTime) %>% summarise(mean_time = mean(playlength))

perall %>% ggplot(aes(x = totalTime, y = mean_time)) +
  geom_point() + 
 geom_smooth(method = "lm")

time_to_shoot.lm <- lm(perall$mean_time ~ perall$totalTime)

summary(time_to_shoot.lm) #slope is .0001569, so .45 of a second longer at the end of the game than the beginning? Hmm.

#shooting % by time
shotpct <- shots %>% group_by(totalTime) %>% 
  summarise(shotpct = sum(result == "made") / (sum(result == "made") + sum(result == "missed")),
            n = n())


shotpct %>% ggplot(aes(x = totalTime, 
                       y = shotpct)) + 
  geom_point() +
  geom_smooth(method = "lm")

shotpct %>% ggplot(aes(x = shotpct)) + geom_histogram()

shotpct.lm <- lm(shotpct$shotpct ~ shotpct$totalTime)
summary(shotpct.lm)

#how to see if shooter is home or away?
for(i in 1:14040) {
  if(shots$player[i] %in% c(shots$a1[i], shots$a2[i], shots$a3[i], shots$a4[i], shots$a5[i])) {shots$homeaway[i] <- "away"} else{shots$homeaway[i] <- "home"}
}

#need to reset score diff when there's a different game
diff <- shots %>% group_by(game_id) %>% 
  summarise(diff = if_else(
    homeaway == "home",
    (lag(home_score) - lag(away_score)),
    (lag(away_score) - lag(home_score))
    ),
    totalTime = totalTime
    )  %>%  ungroup()                            

shots2 <- left_join(shots, diff, by = c("game_id", "totalTime")) 
#somehow this added 94 rows, but whatev

#make the starting NA = 0
shots2$diff = replace_na(shots2$diff, 0)

#group by point diff and see time to shoot
shotdiff <-  shots2 %>% group_by(diff, period) %>% 
  summarise(ttshoot = mean(playlength),
            n = n()
            ) %>% 
  ungroup()

shotdiff %>% filter(n > 20) %>% ggplot(aes(x = diff, 
                        y = ttshoot, 
                        color = as.factor(period)
                        )
                    ) +
  geom_point() +
  facet_wrap(~ period)

```

#nbastatR tutorial
```{r}
selectedSeasons <- c(2019:2022)

gameIds_Reg <- suppressWarnings(seasons_schedule(seasons = selectedSeasons, season_types = "Regular Season") %>% select(idGame, slugMatchup))

gameIds_PO <- suppressWarnings(seasons_schedule(seasons = selectedSeasons, season_types = "Playoffs") %>% select(idGame, slugMatchup))

gameIds_all <- rbind(gameIds_Reg, gameIds_PO)

head(gameIds_all)
tail(gameIds_all)


P_gamelog_reg <- suppressWarnings(game_logs(seasons = selectedSeasons, league = "NBA", result_types = "player", season_types = "Regular Season"))

P_gamelog_po <- suppressWarnings(game_logs(seasons = selectedSeasons, league = "NBA", result_types = "player", season_types = "Playoffs"))

P_gamelog_all <- rbind(P_gamelog_reg, P_gamelog_po)

remove(P_gamelog_reg, P_gamelog_po)

T_gamelog_reg <- suppressWarnings(game_logs(seasons = selectedSeasons, league = "NBA", result_types = "team", season_types = "Regular Season"))

T_gamelog_po <- suppressWarnings(game_logs(seasons = selectedSeasons, league = "NBA", result_types = "team", season_types = "Playoffs"))


T_gamelog_all <- rbind(T_gamelog_reg, T_gamelog_po)
remove(T_gamelog_po, T_gamelog_reg)

Tbox <- T_gamelog_reg %>%
  group_by("Season"=yearSeason, "Team"=slugTeam) %>%
  dplyr::summarise(GP=n(), MIN=sum(round(minutesTeam/5)),
                   PTS=sum(ptsTeam),
                   W=sum(outcomeGame=="W"), 
                   L=sum(outcomeGame=="L"),
                   P2M=sum(fg2mTeam), P2A=sum(fg2aTeam), 
                   P2p=P2M/P2A,
                   P3M=sum(fg3mTeam), P3A=sum(fg3aTeam), 
                   P3p=P3M/P3A,
                   FTM=sum(ftmTeam), FTA=sum(ftaTeam), 
                   FTp=FTM/FTA,
                   OREB=sum(orebTeam), DREB=sum(drebTeam), 
                   AST=sum(astTeam),
                   TOV=sum(tovTeam), STL=sum(stlTeam), 
                   BLK=sum(blkTeam),
                   PF=sum(pfTeam), PM=sum(plusminusTeam)) %>%
  as.data.frame() %>% 
  ungroup()

Obox <- T_gamelog_reg %>%
  group_by("Season"=yearSeason, "Team"=slugOpponent) %>%
  dplyr::summarise(GP=n(), MIN=sum(round(minutesTeam/5)),
                   PTS=sum(ptsTeam),
                   W=sum(outcomeGame=="L"), 
                   L=sum(outcomeGame=="W"),
                   P2M=sum(fg2mTeam), P2A=sum(fg2aTeam), 
                   P2p=P2M/P2A,
                   P3M=sum(fg3mTeam), P3A=sum(fg3aTeam), 
                   P3p=P3M/P3A,
                   FTM=sum(ftmTeam), FTA=sum(ftaTeam), 
                   FTp=FTM/FTA,
                   OREB=sum(orebTeam), DREB=sum(drebTeam), 
                   AST=sum(astTeam),
                   TOV=sum(tovTeam), STL=sum(stlTeam), 
                   BLK=sum(blkTeam),
                   PF=sum(pfTeam), PM=sum(plusminusTeam)) %>%
  as.data.frame() %>% 
  ungroup()

Pbox <- P_gamelog_reg %>%
  group_by("Season"=yearSeason, "Team"=slugTeam, "Player"=namePlayer) %>%
  dplyr::summarise(GP=n(), MIN=sum(minutes), PTS=sum(pts),
                   P2M=sum(fg2m), P2A=sum(fg2a), P2p=100*P2M/P2A,
                   P3M=sum(fg3m), P3A=sum(fg3a), P3p=100*P3M/P3A,
                   FTM=sum(ftm), FTA=sum(fta), FTp=100*FTM/FTA,
                   OREB=sum(oreb), DREB=sum(dreb), AST=sum(ast),
                   TOV=sum(tov), STL=sum(stl), BLK=sum(blk),
                   PF=sum(pf)) %>%
  as.data.frame() %>% 
  ungroup()

View(Pbox[Pbox$Player=="LeBron James",])

teamSelected <- "BOS"
Pbox.sel <- subset(Pbox, Team==teamSelected &
                     MIN>=1000)
seasonSelected <- 2022

barline(data=Pbox.sel[Pbox.sel$Season==seasonSelected,], 
        id="Player",
        bars=c("P2M","P3M","FTM"), line="PTS",
        order.by="PTS", labels.bars=c("2PM","3PM","FTM"),
        title=teamSelected) 
Pbox.sel$P_Yr = paste(Pbox.sel$Player, Pbox.sel$Season, sep = ", ")

#plot of assists, turnovers and points per min for Boston all years
patBos <- Pbox.sel %>% ggplot(aes(x = AST / MIN, y = TOV / MIN, color = PTS / MIN)) +
  scale_color_gradient(low = "white",
                       high = "dark green") +
  geom_point() +
  expand_limits(x = c(0, .25)) +
  geom_text(label = Pbox.sel$P_Yr,
            size = 3) +
  labs(x = "Assists per Min",
       y = "Turnovers per Min",
       title = "Points, Assists and Turnovers - Boston Celtics",
       subtitle = "2019 - 2022")

#2pt%, 3pt%, total shots and free throw% all teams 2022
Tbox22 <- Tbox %>% filter(Season == 2022)
Tbox22 %>% 
  ggplot(aes(x = P2p, y = P3p, 
             color = FTp, 
             size = (P2A + P3A + FTA) / GP)) +
  geom_point() +
  geom_vline(xintercept = mean(Tbox22$P2p)) +
  geom_hline(yintercept = mean(Tbox$P3p)) +
  geom_text(label = Tbox22$Team,
            size = 3,
            nudge_y = 0.0015) +
  scale_color_continuous(type = "viridis") +
  labs(title = "Shooting Stats by Team, 2022",
       x = "2pt%",
       y = "3pt%",
       color = "Free Throw %",
       size = "Shots per Game",
       caption = "@jmeerse  data by BasketballAnalyzeR")
 
 
 
#players on the last 4 teams
fin4 <- Pbox %>% filter(Season == 2022, Team %in% c("BOS", "GSW", "MIA", "DAL"), MIN > 1500)

fin4$tcol = case_when(fin4$Team == "BOS" ~ "green",
                      fin4$Team == "GSW" ~ "gold",
                      fin4$Team == "MIA" ~ "red",
                      fin4$Team == "DAL" ~ "blue")

fin4 %>% ggplot(aes(x = DREB / MIN, y = STL / MIN, 
                    color = BLK / MIN, size = MIN)) + 
  geom_point() +
  geom_text(label = fin4$Player,
            color = fin4$tcol,
            nudge_y = 0.001) +
  labs(x = "Def. Reb per Min",
       y = "Steals per Min",
       color = "Blocks per Min", 
       size = "Total Minutes",
       title = "NBA Conf Finals Players 2022",
       caption = "@jmeerse  data: BasketballAnalyzeR")

#k-means clustering

seasonSelected <- 2022
Tbox.sel <- subset(Tbox, Season==seasonSelected)
Obox.sel <- subset(Obox,Season==seasonSelected)

FF <- fourfactors(Tbox.sel,Obox.sel)
OD.Rtg <- FF$ORtg/FF$DRtg
F1.r <- FF$F1.Off/FF$F1.Def
F2.r <- FF$F2.Def/FF$F2.Off
F3.Off <- FF$F3.Off
F3.Def <- FF$F3.Def
P3M.ff <- Tbox.sel$P3M
STL.r <- Tbox.sel$STL/Obox.sel$STL
data <- data.frame(OD.Rtg, F1.r, F2.r, F3.Off, F3.Def, P3M.ff, STL.r)

RNGkind(sample.kind="Rounding")
set.seed(29)
kclu1 <- kclustering(data)
plot(kclu1)

#use 7 clusters (need to research why)
set.seed(29)
kclu2 <- kclustering(data, labels=Tbox.sel$Team, k=6)
plot(kclu2)

#now make bubble plots 
kclu2.W <- tapply(Tbox.sel$W, kclu2$Subjects$Cluster, mean)

cluster <- as.factor(kclu2$Subjects$Cluster)
Xbubble <- data.frame(Team=Tbox.sel$Team, PTS=Tbox.sel$PTS,
                      PTS.Opp=Obox.sel$PTS, cluster,
                      W=Tbox.sel$W)


labs <- c("PTS", "PTS.Opp", "cluster", "Wins")
bubbleplot(Xbubble, id="Team", x="PTS", y="PTS.Opp",
           col="cluster", size="W", labels=labs,
           title=paste0("NBA Team Clusters - ",seasonSelected))#

```
